version: '3.8'

services:
  api:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.8
    ports:
      - "8000:80"
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
